apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voiceflow-slack.serviceAccountName" . }}
  labels:
    {{- include "voiceflow-slack.labels" . | nindent 4 }}
type: Opaque
data:
  voiceflow-api-key: {{ .Values.settings.voiceflow.api_key | b64enc | quote }}
  slack-app-token: {{ .Values.settings.slack.app_token | b64enc | quote }}
  slack-bot-token: {{ .Values.settings.slack.bot_token | b64enc | quote }}
  slack-signing-secret: {{ .Values.settings.slack.signing_secret | b64enc | quote }}
